import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const code=ts.transpileModule(readFileSync(new URL('../supabase/functions/_shared/emailCore.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const core=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const fakeJwt='eyJhbGciOiJub25lIn0.'+Buffer.from('{"role":"service_role"}').toString('base64url')+'.fake';
assert.equal(core.isTrustedWorkerRequest(new Request('https://local',{headers:{Authorization:'Bearer '+fakeJwt}}),'real-secret','cron-secret'),false);
assert.equal(core.isTrustedWorkerRequest(new Request('https://local',{headers:{Authorization:'Bearer real-secret'}}),'real-secret','cron-secret'),true);
assert.equal(core.isTrustedWorkerRequest(new Request('https://local',{headers:{'x-cron-secret':'cron-secret'}}),'real-secret','cron-secret'),true);
assert.equal(core.safeEqual('', ''),false);
for (const sender of ['', 'bad', 'onboarding@resend.dev','Name <test@gmail.com>']) assert.equal(core.resolveSender(sender),null);
assert.equal(core.resolveSender('DYP <hello@notify.example.org>').domain,'notify.example.org');
const prefs={program_emails_enabled:true,session_reminders_enabled:false,accountability_reminders_enabled:false,referral_updates_enabled:false};
for(const type of ['program_session_1h','session_24h','coach_assigned','referral_paid']) assert.equal(core.emailAllowedByPrefs(type,prefs),false,type);
assert.equal(core.emailAllowedByPrefs('group_digest_daily',{...prefs,group_digest:'off'}),false);
assert.equal(core.emailAllowedByPrefs('welcome',{...prefs,program_emails_enabled:false}),false);
assert.equal(core.nextRetryState(5).status,'failed');
assert.equal(core.nextRetryState(2,new Date('2026-01-01')).nextAttemptAt,'2026-01-01T00:10:00.000Z');
const html=core.renderEmail({appUrl:'https://dyp-goals.lovable.app',title:'<unsafe>',bodyHtml:'<p>Safe</p>',ctaLabel:'<click>',ctaPath:'//evil.example/'});
assert(html.includes('&lt;unsafe&gt;'));assert(!html.includes('href="https://evil.example'));assert(html.includes('/profile#notifications'));
let request;
const receipt=await core.sendViaResend({directApiKey:'private-test-only',from:'hello@example.org',to:'user@example.org',subject:'test',html:'<p>test</p>',idempotencyKey:'queue:one'},async (url,args)=>{request={url,args};return new Response('{"id":"receipt-one"}',{status:200})});
assert.equal(request.url,'https://api.resend.com/emails');assert.equal(request.args.headers.Authorization,'Bearer private-test-only');assert.equal(request.args.headers['Idempotency-Key'],'queue:one');assert.equal(request.args.headers['X-Connection-Api-Key'],undefined);assert.equal(receipt.providerMessageId,'receipt-one');
await assert.rejects(()=>core.sendViaResend({directApiKey:'fake',from:'a@example.org',to:'b@example.org',subject:'x',html:'x',idempotencyKey:'one'},async()=>new Response('{"message":"Domain unverified"}',{status:403})),e=>e instanceof core.ProviderError && core.isPermanentProviderError(e.status));
await assert.rejects(()=>core.sendViaResend({directApiKey:'fake',from:'a@example.org',to:'b@example.org',subject:'x',html:'x',idempotencyKey:'one'},async()=>new Response('{}',{status:200})),/receipt/);
console.log('PASS: worker authorization, sender validation, opt-out rules, bounded retries, safe links and mocked Resend acceptance/idempotency.');
const {PGlite}=await import(process.env.PGLITE_MODULE_PATH||'@electric-sql/pglite');
const db=new PGlite();
const user='11111111-1111-1111-1111-111111111111',admin='22222222-2222-2222-2222-222222222222';
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema cron;
create table auth.users(id uuid primary key,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create type app_role as enum('admin','user');
create function has_role(uuid,app_role) returns boolean language sql stable as $$select $1='${admin}'::uuid and $2='admin'$$;
create function consume_edge_rate_limit(text,integer,integer) returns table(allowed boolean) language sql as $$select true$$;
create table profiles(id uuid primary key);
create table notification_preferences(user_id uuid primary key,program_emails_enabled boolean default true);
create table user_notifications(id uuid default gen_random_uuid(),user_id uuid,notification_type text,title text,body text,action_label text,action_path text,metadata jsonb);
create table email_notification_queue(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id),notification_type text,subject text,body_html text,action_label text,action_path text,status text default 'pending' check(status in ('pending','processing','sent','failed','cancelled')),attempt_count integer default 0,last_error text default '',created_at timestamptz default now(),processed_at timestamptz);
alter table email_notification_queue enable row level security;
grant select on email_notification_queue to authenticated;create policy admin_queue on email_notification_queue for select to authenticated using(has_role(auth.uid(),'admin'));
create table program_cohorts(id uuid primary key,name text);
create table program_enrollments(id uuid primary key,user_id uuid,cohort_id uuid);
create table participant_testimonials(id uuid primary key,user_id uuid,status text,publish_consent boolean);
create table cron.job(jobid integer,jobname text,schedule text,active boolean);create table cron.job_run_details(jobid integer,status text,start_time timestamptz,end_time timestamptz,return_message text);
grant usage on schema public,auth to anon,authenticated,service_role;
insert into auth.users values('${user}',now()),('${admin}',now());insert into profiles values('${user}'),('${admin}');`);
for(const path of ['20261010135500_automatic_email_system.sql','20261010141500_email_runtime_safety.sql']) await db.exec(readFileSync(new URL('../supabase/migrations/'+path,import.meta.url),'utf8'));
await db.query(`select queue_transactional_email('${user}','welcome','Welcome','Body','Open','/journey','welcome:${user}')`);
await db.query(`select queue_transactional_email('${user}','welcome','Welcome','Body','Open','/journey','welcome:${user}')`);
assert.equal((await db.query('select count(*)::integer n from email_notification_queue')).rows[0].n,1);
assert.equal((await db.query('select count(*)::integer n from user_notifications')).rows[0].n,1);
const claimed=(await db.query('select * from claim_email_batch(10,15)')).rows;assert.equal(claimed.length,1);assert.equal(claimed[0].attempt_count,1);
assert.equal((await db.query('select * from claim_email_batch(10,15)')).rows.length,0);
await db.exec("update email_notification_queue set locked_at=now()-interval '16 minutes'");assert.equal((await db.query('select * from claim_email_batch(10,15)')).rows[0].attempt_count,2);
await db.exec("update email_notification_queue set locked_at=now()-interval '23 hours'");assert.equal((await db.query('select * from claim_email_batch(10,15)')).rows.length,0);
assert.equal((await db.query('select status from email_notification_queue')).rows[0].status,'failed');
await db.exec(`set role authenticated;set request.jwt.claim.sub='${user}';`);
assert.equal((await db.query('select * from email_notification_queue')).rows.length,0);
await assert.rejects(()=>db.query('select admin_email_system_overview()'),/Admin role/);
await assert.rejects(()=>db.query('select claim_email_batch()'),/permission denied/);
await db.exec("set request.jwt.claim.sub=''");await assert.rejects(()=>db.query('select admin_email_system_overview()'),/Admin role/);
await db.exec(`set request.jwt.claim.sub='${admin}'`);assert.equal((await db.query('select admin_email_system_overview() o')).rows[0].o.counts.failed,1);
await db.exec('reset role');
// Confirmed OAuth account inserted before profile must still get a welcome once its profile is created.
const oauth='33333333-3333-3333-3333-333333333333';await db.exec(`insert into auth.users values('${oauth}',now());insert into profiles values('${oauth}')`);
assert.equal((await db.query(`select count(*)::integer n from email_notification_queue where user_id='${oauth}'`)).rows[0].n,1);
await db.exec(`insert into notification_preferences values('${user}',false)`);
await db.query(`select queue_transactional_email('${user}','testimonial_received','Story','Body','Open','/profile','story:optout')`);
assert.equal((await db.query("select count(*)::integer n from email_notification_queue where dedupe_key='story:optout'")).rows[0].n,0);
await db.close();console.log('PASS: PostgreSQL deduplication, atomic non-overlapping claims, bounded stale recovery, admin-only queue/actions, OAuth welcome and opt-out.');
