import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

interface RefinedGoal {
  title: string;
  description: string;
  actionSteps: string[];
  timeline: string;
  successMetrics: string[];
}

interface GoalsPDFDocumentProps {
  goals: RefinedGoal[];
  userName?: string;
  targetYear?: number;
}

// Create styles for PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2 solid #8B5CF6',
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#8B5CF6',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  date: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  goalSection: {
    marginBottom: 30,
    borderLeft: '4 solid #D946EF',
    paddingLeft: 15,
  },
  goalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#8B5CF6',
    marginBottom: 8,
    marginTop: 12,
  },
  description: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
    marginBottom: 12,
  },
  stepItem: {
    fontSize: 10,
    color: '#4B5563',
    marginBottom: 8,
    paddingLeft: 20,
    lineHeight: 1.5,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  checkbox: {
    width: 12,
    height: 12,
    border: '1.5 solid #8B5CF6',
    marginRight: 8,
    marginTop: 2,
  },
  metricItem: {
    fontSize: 9,
    color: '#6B7280',
    marginBottom: 4,
    paddingLeft: 15,
  },
  timeline: {
    fontSize: 11,
    color: '#059669',
    fontWeight: 'bold',
    backgroundColor: '#D1FAE5',
    padding: 8,
    borderRadius: 4,
    marginTop: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 9,
    borderTop: '1 solid #E5E7EB',
    paddingTop: 10,
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 15,
  },
});

export const GoalsPDFDocument = ({ goals, userName = 'Goal Achiever', targetYear = new Date().getFullYear() + 1 }: GoalsPDFDocumentProps) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>DYP GOALS {targetYear}</Text>
          <Text style={styles.subtitle}>Your Comprehensive Action Plan</Text>
          <Text style={styles.date}>Created on {currentDate}</Text>
        </View>

        {/* Goals */}
        {goals.map((goal, index) => (
          <View key={index} style={styles.goalSection} wrap={false}>
            <Text style={styles.goalTitle}>
              Goal {index + 1}: {goal.title}
            </Text>

            {/* Description */}
            <Text style={styles.sectionTitle}>Description</Text>
            <Text style={styles.description}>{goal.description}</Text>

            {/* Timeline */}
            <Text style={styles.timeline}>⏱ Timeline: {goal.timeline}</Text>

            {/* Action Steps with Checkboxes */}
            <Text style={styles.sectionTitle}>Action Steps</Text>
            {goal.actionSteps.map((step, stepIndex) => (
              <View key={stepIndex} style={styles.checkboxContainer}>
                <View style={styles.checkbox} />
                <Text style={styles.stepItem}>{step}</Text>
              </View>
            ))}

            {/* Success Metrics */}
            <Text style={styles.sectionTitle}>Success Metrics</Text>
            {goal.successMetrics.map((metric, metricIndex) => (
              <Text key={metricIndex} style={styles.metricItem}>
                • {metric}
              </Text>
            ))}

            {index < goals.length - 1 && <View style={styles.divider} />}
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by DYP AI Coach | Discover Your Purpose
        </Text>
      </Page>
    </Document>
  );
};
