import { CheckCircle2 } from "lucide-react";
import { stripAIFormatting } from "@/components/AIFormattedText";

interface RefinedGoal {
  title: string;
  description: string;
  actionSteps: string[];
  timeline: string;
  successMetrics: string[];
}

interface PrintableGoalsProps {
  goals: RefinedGoal[];
  targetYear?: number;
}

export const PrintableGoals = ({ goals, targetYear = new Date().getFullYear() + 1 }: PrintableGoalsProps) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="hidden print:block bg-white text-black p-8 max-w-[210mm] mx-auto">
      <style>
        {`
          @media print {
            @page {
              size: A4;
              margin: 20mm;
            }
            body {
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
            }
            .print\\:block {
              display: block !important;
            }
            .hidden {
              display: none !important;
            }
          }
        `}
      </style>

      {/* Header */}
      <div className="border-b-4 border-purple-600 pb-4 mb-8">
        <h1 className="text-4xl font-bold text-purple-600 mb-2">DYP GOALS {targetYear}</h1>
        <p className="text-xl text-gray-600">Your Comprehensive Action Plan</p>
        <p className="text-sm text-gray-400 mt-2">Created on {currentDate}</p>
      </div>

      {/* Goals */}
      <div className="space-y-8">
        {goals.map((goal, index) => (
          <div key={index} className="border-l-4 border-pink-500 pl-4 break-inside-avoid">
            <h2 className="text-2xl font-bold text-gray-900 mb-3">
              Goal {index + 1}: {stripAIFormatting(goal.title)}
            </h2>

            {/* Description */}
            <div className="mb-4">
              <h3 className="text-sm font-bold text-purple-600 mb-2 uppercase">Description</h3>
              <p className="text-gray-700 leading-relaxed">{stripAIFormatting(goal.description)}</p>
            </div>

            {/* Timeline */}
            <div className="bg-green-50 border-l-4 border-green-500 p-3 mb-4">
              <p className="text-sm font-bold text-green-700">
                ⏱ Timeline: {stripAIFormatting(goal.timeline)}
              </p>
            </div>

            {/* Action Steps with Checkboxes */}
            <div className="mb-4">
              <h3 className="text-sm font-bold text-purple-600 mb-2 uppercase">Action Steps</h3>
              <div className="space-y-2">
                {goal.actionSteps.map((step, stepIndex) => (
                  <div key={stepIndex} className="flex items-start gap-2">
                    <div className="w-4 h-4 border-2 border-purple-600 rounded mt-1 flex-shrink-0" />
                    <p className="text-sm text-gray-700 flex-1">{stripAIFormatting(step)}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Success Metrics */}
            <div className="mb-4">
              <h3 className="text-sm font-bold text-purple-600 mb-2 uppercase">Success Metrics</h3>
              <ul className="space-y-1 ml-4">
                {goal.successMetrics.map((metric, metricIndex) => (
                  <li key={metricIndex} className="text-sm text-gray-600">
                    • {stripAIFormatting(metric)}
                  </li>
                ))}
              </ul>
            </div>

            {index < goals.length - 1 && (
              <div className="border-t border-gray-200 my-6" />
            )}
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-12 pt-4 border-t border-gray-300 text-center text-xs text-gray-400">
        Generated by DYP AI Coach | Discover Your Purpose
      </div>
    </div>
  );
};
