import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

interface TimePlan {
  yearlyPlan: any;
  monthlyPlan: any;
  weeklyPlan: any;
  dailyPlan: any;
  summary: any;
}

interface TimePlanPDFDocumentProps {
  plan: TimePlan;
  goal: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #8B5CF6',
    paddingBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#8B5CF6',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
  },
  goalSection: {
    backgroundColor: '#F3F4F6',
    padding: 12,
    borderRadius: 4,
    marginBottom: 20,
  },
  goalLabel: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 4,
  },
  goalText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
    marginTop: 20,
    borderBottom: '1 solid #E5E7EB',
    paddingBottom: 8,
  },
  quarterCard: {
    marginBottom: 12,
    padding: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 4,
    borderLeft: '3 solid #8B5CF6',
  },
  quarterTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#8B5CF6',
    marginBottom: 6,
  },
  listItem: {
    fontSize: 10,
    color: '#374151',
    marginBottom: 4,
    paddingLeft: 12,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  monthCard: {
    width: '48%',
    padding: 8,
    backgroundColor: '#F9FAFB',
    borderRadius: 4,
    marginBottom: 8,
  },
  monthTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  monthFocus: {
    fontSize: 9,
    color: '#8B5CF6',
    marginBottom: 4,
  },
  weekCard: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 4,
  },
  weekTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 8,
  },
  dayRow: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingBottom: 4,
    borderBottom: '1 solid #E5E7EB',
  },
  dayName: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#6B7280',
    width: 60,
  },
  dayActivities: {
    fontSize: 9,
    color: '#374151',
    flex: 1,
  },
  dayHours: {
    fontSize: 9,
    color: '#8B5CF6',
    width: 30,
    textAlign: 'right',
  },
  timeBlock: {
    flexDirection: 'row',
    marginBottom: 6,
    padding: 6,
    backgroundColor: '#F3F4F6',
    borderRadius: 2,
  },
  timeBlockTime: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#6B7280',
    width: 80,
  },
  timeBlockActivity: {
    fontSize: 9,
    color: '#374151',
    flex: 1,
  },
  timeBlockCategory: {
    fontSize: 8,
    color: '#8B5CF6',
    width: 60,
    textAlign: 'right',
  },
  summaryCard: {
    padding: 12,
    backgroundColor: '#EEF2FF',
    borderRadius: 4,
    marginTop: 15,
  },
  summaryItem: {
    fontSize: 10,
    color: '#374151',
    marginBottom: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 8,
    borderTop: '1 solid #E5E7EB',
    paddingTop: 10,
  },
  pageNumber: {
    fontSize: 8,
    color: '#9CA3AF',
  },
});

export const TimePlanPDFDocument = ({ plan, goal }: TimePlanPDFDocumentProps) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <Document>
      {/* Page 1: Yearly Plan */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>DYP TIME PLAN</Text>
          <Text style={styles.subtitle}>Comprehensive Goal Achievement Schedule</Text>
          <Text style={{ fontSize: 9, color: '#9CA3AF' }}>Created on {currentDate}</Text>
        </View>

        <View style={styles.goalSection}>
          <Text style={styles.goalLabel}>YOUR GOAL</Text>
          <Text style={styles.goalText}>{goal}</Text>
        </View>

        <Text style={styles.sectionTitle}>YEARLY PLAN</Text>
        {plan.yearlyPlan?.quarters?.map((quarter: any, idx: number) => (
          <View key={idx} style={styles.quarterCard}>
            <Text style={styles.quarterTitle}>Q{quarter.quarter}: {quarter.focus}</Text>
            {quarter.milestones?.map((milestone: string, mIdx: number) => (
              <Text key={mIdx} style={styles.listItem}>• {milestone}</Text>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>Generated by DYP AI Coach | Page 1</Text>
      </Page>

      {/* Page 2: Monthly Plan */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>MONTHLY PLAN</Text>
        <View style={styles.monthGrid}>
          {plan.monthlyPlan?.months?.slice(0, 6).map((month: any, idx: number) => (
            <View key={idx} style={styles.monthCard}>
              <Text style={styles.monthTitle}>{month.month}</Text>
              <Text style={styles.monthFocus}>{month.focus}</Text>
              {month.goals?.slice(0, 2).map((g: string, gIdx: number) => (
                <Text key={gIdx} style={{ fontSize: 8, color: '#6B7280', marginBottom: 2 }}>• {g}</Text>
              ))}
            </View>
          ))}
        </View>

        <View style={styles.monthGrid}>
          {plan.monthlyPlan?.months?.slice(6, 12).map((month: any, idx: number) => (
            <View key={idx} style={styles.monthCard}>
              <Text style={styles.monthTitle}>{month.month}</Text>
              <Text style={styles.monthFocus}>{month.focus}</Text>
              {month.goals?.slice(0, 2).map((g: string, gIdx: number) => (
                <Text key={gIdx} style={{ fontSize: 8, color: '#6B7280', marginBottom: 2 }}>• {g}</Text>
              ))}
            </View>
          ))}
        </View>

        <Text style={styles.footer}>Generated by DYP AI Coach | Page 2</Text>
      </Page>

      {/* Page 3: Weekly Plan */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>WEEKLY PLAN SAMPLES</Text>
        {plan.weeklyPlan?.sampleWeeks?.slice(0, 2).map((week: any, idx: number) => (
          <View key={idx} style={styles.weekCard}>
            <Text style={styles.weekTitle}>Week {week.weekNumber}: {week.theme}</Text>
            {week.tasks?.map((task: any, tIdx: number) => (
              <View key={tIdx} style={styles.dayRow}>
                <Text style={styles.dayName}>{task.day}</Text>
                <Text style={styles.dayActivities}>{task.activities?.join(', ')}</Text>
                <Text style={styles.dayHours}>{task.hours}h</Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>Generated by DYP AI Coach | Page 3</Text>
      </Page>

      {/* Page 4: Daily Plan */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>DAILY SCHEDULE TEMPLATE</Text>
        
        <Text style={{ fontSize: 12, fontWeight: 'bold', color: '#1F2937', marginBottom: 8 }}>Weekday Schedule</Text>
        {plan.dailyPlan?.weekdayTemplate?.timeBlocks?.slice(0, 10).map((block: any, idx: number) => (
          <View key={idx} style={styles.timeBlock}>
            <Text style={styles.timeBlockTime}>{block.startTime} - {block.endTime}</Text>
            <Text style={styles.timeBlockActivity}>{block.activity}</Text>
            <Text style={styles.timeBlockCategory}>{block.category}</Text>
          </View>
        ))}

        <Text style={{ fontSize: 12, fontWeight: 'bold', color: '#1F2937', marginBottom: 8, marginTop: 15 }}>Weekend Schedule</Text>
        {plan.dailyPlan?.weekendTemplate?.timeBlocks?.slice(0, 8).map((block: any, idx: number) => (
          <View key={idx} style={styles.timeBlock}>
            <Text style={styles.timeBlockTime}>{block.startTime} - {block.endTime}</Text>
            <Text style={styles.timeBlockActivity}>{block.activity}</Text>
            <Text style={styles.timeBlockCategory}>{block.category}</Text>
          </View>
        ))}

        <View style={styles.summaryCard}>
          <Text style={{ fontSize: 11, fontWeight: 'bold', color: '#1F2937', marginBottom: 6 }}>Summary</Text>
          <Text style={styles.summaryItem}>Weekly Commitment: {plan.summary?.totalWeeklyCommitment || 0} hours</Text>
          <Text style={styles.summaryItem}>Estimated Completion: {plan.summary?.estimatedCompletionDate || 'TBD'}</Text>
        </View>

        <Text style={styles.footer}>Generated by DYP AI Coach | Page 4</Text>
      </Page>
    </Document>
  );
};
